-- CREATE DATABASE IF NOT EXISTS `HEADERDB`;
-- GRANT ALL PRIVILEGES ON HEADERDB.* TO 'ohgiraffers'@'%';

-- Use SHOPDB database
USE `HEADERDB`;

-- drop table
DROP TABLE IF EXISTS TBL_SHOP_MSG_HISTORY;
DROP TABLE IF EXISTS TBL_MSG_SEND_BATCH;
DROP TABLE IF EXISTS TBL_VISITORS;
DROP TABLE IF EXISTS TBL_SALES;
DROP TABLE IF EXISTS TBL_RESERVATION;
DROP TABLE IF EXISTS TBL_MESSAGE_TEMPLATE;
DROP TABLE IF EXISTS TBL_MENU;
DROP TABLE IF EXISTS TBL_MENU_CATEGORY;
DROP TABLE IF EXISTS TBL_SHOP_HOLIDAY;
DROP TABLE IF EXISTS TBL_SHOP;
DROP TABLE IF EXISTS TBL_SHOP_CATEGORY;
DROP TABLE IF EXISTS TBL_USER;

-- USER table
CREATE TABLE IF NOT EXISTS `TBL_USER`
(
    `USER_CODE`  INT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID`    VARCHAR(20)  NULL COMMENT '아이디',
    `USER_PWD`   VARCHAR(255) NULL COMMENT '비밀번호',
    `IS_ADMIN`   BOOLEAN      NOT NULL DEFAULT 0 COMMENT '관리자여부',
    `USER_NAME`  VARCHAR(255) NOT NULL COMMENT '이름',
    `USER_PHONE` VARCHAR(20)  NOT NULL COMMENT '전화번호',
    `BIRTHDAY`   DATE         NULL COMMENT '고객생일',
    `IS_LEAVE`   BOOLEAN      NOT NULL DEFAULT 0 COMMENT '탈퇴여부'
);

-- SHOP_CATEGORY table
CREATE TABLE IF NOT EXISTS `TBL_SHOP_CATEGORY`
(
    `CATEGORY_CODE` INT PRIMARY KEY AUTO_INCREMENT,
    `CATEGORY_NAME` VARCHAR(50) NOT NULL COMMENT '카테고리 이름'
);

-- SHOP table
CREATE TABLE IF NOT EXISTS `TBL_SHOP`
(
    `SHOP_CODE`     INT PRIMARY KEY AUTO_INCREMENT,
    `CATEGORY_CODE` INT            NOT NULL COMMENT '샵 유형 코드',
    `ADMIN_CODE`    INT            NOT NULL COMMENT '관리자 코드',
    `SHOP_NAME`     VARCHAR(50)    NOT NULL COMMENT '샵 이름',
    `SHOP_PHONE`    VARCHAR(20)    NOT NULL COMMENT '샵 전화번호',
    `SHOP_LOCATION` VARCHAR(255)   NOT NULL COMMENT '샵 주소',
    `SHOP_LONG`     DECIMAL(10, 7) NOT NULL COMMENT '샵 경도',
    `SHOP_LA`       DECIMAL(10, 7) NOT NULL COMMENT '샵 위도', -- 샵 휴일 테이블 추가 후 샵 상태 컬럼 삭제
    `SHOP_OPEN`     VARCHAR(5)     NOT NULL COMMENT '샵 운영시간',
    `SHOP_CLOSE`    VARCHAR(5)     NOT NULL COMMENT '샵 닫는시간',
    `IS_ACTIVE`     BOOLEAN        NOT NULL DEFAULT 1 COMMENT '활성 여부'
);

CREATE TABLE IF NOT EXISTS `TBL_SHOP_HOLIDAY`
(
    `SHOP_HOL_CODE` INT PRIMARY KEY AUTO_INCREMENT,
    `SHOP_CODE`    INT     NOT NULL,
    `HOL_START_DATE`   DATE    NOT NULL COMMENT '적용 시작 날짜',
    `HOL_END_DATE`     DATE    NULL COMMENT '적용 종료 날짜',
    `IS_HOL_REPEAT`    BOOLEAN NOT NULL DEFAULT 0 COMMENT '반복 여부'
);

-- MENU_CATEGORY table (modified to include SHOP_CODE as FK and composite PK)
CREATE TABLE IF NOT EXISTS `TBL_MENU_CATEGORY`
(
    `CATEGORY_CODE` INT         NOT NULL COMMENT '카테고리 코드',
    `SHOP_CODE`     INT         NOT NULL COMMENT '샵 코드',
    `CATEGORY_NAME` VARCHAR(40) NOT NULL COMMENT '카테고리명',
    `MENU_COLOR`    VARCHAR(20) NOT NULL COMMENT '대표 색상',
    `IS_ACTIVE`     BOOLEAN     NOT NULL DEFAULT 1 COMMENT '활성 여부',
    PRIMARY KEY (`CATEGORY_CODE`, `SHOP_CODE`)
);

-- MENU table (modified to remove SHOP_CODE direct FK, now references through MENU_CATEGORY)
CREATE TABLE IF NOT EXISTS `TBL_MENU`
(
    `MENU_CODE`     INT PRIMARY KEY AUTO_INCREMENT,
    `CATEGORY_CODE` INT         NOT NULL COMMENT '카테고리 코드',
    `SHOP_CODE`     INT         NOT NULL COMMENT '샵 코드',
    `MENU_NAME`     VARCHAR(40) NOT NULL COMMENT '시술명',
    `MENU_PRICE`    INT         NOT NULL COMMENT '시술가격',
    `EST_TIME`      INT         NOT NULL COMMENT '예상소요시간',
    `IS_ACTIVE`     BOOLEAN     NOT NULL DEFAULT 1 COMMENT '활성 여부'
);

-- MESSAGE_TEMPLATE table
CREATE TABLE IF NOT EXISTS `TBL_MESSAGE_TEMPLATE`
(
    `TEMPLATE_CODE`    INT PRIMARY KEY AUTO_INCREMENT,
    `SHOP_CODE`        INT COMMENT '샵 코드',
    `TEMPLATE_TITLE`   VARCHAR(50)  NOT NULL COMMENT '템플릿 제목',
    `TEMPLATE_CONTENT` VARCHAR(255) NOT NULL COMMENT '템플릿 내용',
    `TEMPLATE_TYPE`    VARCHAR(20)  NOT NULL COMMENT '템플릿 타입'
);

-- RESERVATION table
CREATE TABLE IF NOT EXISTS `TBL_RESERVATION`
(
    `RESV_CODE`    INT PRIMARY KEY AUTO_INCREMENT,
    `USER_CODE`    INT          NOT NULL COMMENT '회원코드',
    `SHOP_CODE`    INT          NOT NULL COMMENT '샵 코드',
    `MENU_CODE`    INT          NOT NULL COMMENT '시술 코드',
    `RESV_DATE`    DATE         NOT NULL COMMENT '예약 날짜',
    `RESV_TIME`    TIME         NOT NULL COMMENT '예약 시간',
    `USER_COMMENT` VARCHAR(255) NULL COMMENT '메모',
    `RESV_STATE`   VARCHAR(20)  NOT NULL DEFAULT '예약확정' COMMENT '예약 상태'
);

-- SALES table (modified PAY_DATETIME to DATETIME)
CREATE TABLE IF NOT EXISTS `TBL_SALES`
(
    `SALES_CODE`      INT PRIMARY KEY AUTO_INCREMENT,
    `RESV_CODE`       INT          NOT NULL COMMENT '예약코드',
    `PAY_AMOUNT`      INT          NOT NULL COMMENT '결제 금액',
    `PAY_METHOD`      VARCHAR(20)  NOT NULL COMMENT '결제 수단',
    `PAY_DATETIME`    DATETIME     NOT NULL COMMENT '결제일시',
    `PAY_STATUS`      VARCHAR(20)  NOT NULL DEFAULT 'COMPLETED' COMMENT '결제상태 (COMPLETED, CANCELLED, PARTIAL_CANCELLED, DELETED)',

    -- 취소 관련 컬럼 추가
    `CANCEL_AMOUNT`   INT          NULL     DEFAULT 0 COMMENT '취소 금액',
    `CANCEL_DATETIME` DATETIME     NULL COMMENT '취소일시',
    `CANCEL_REASON`   VARCHAR(255) NULL COMMENT '취소 사유',
    `FINAL_AMOUNT`    INT          NOT NULL COMMENT '최종 결제 금액 (결제금액 - 취소금액)'
);

-- VISITORS table
CREATE TABLE IF NOT EXISTS `TBL_VISITORS`
(
    `CLIENT_CODE` INT PRIMARY KEY AUTO_INCREMENT,
    `USER_CODE`   INT          NOT NULL COMMENT '회원코드',
    `SHOP_CODE`   INT          NOT NULL COMMENT '샵 코드',
    `MEMO`        VARCHAR(255) NULL COMMENT '메모',
    `SENDABLE`    BOOLEAN      NOT NULL DEFAULT 0 COMMENT '광고성수신여부',
    `IS_ACTIVE`   BOOLEAN      NOT NULL DEFAULT 1 COMMENT '활성여부'
);

-- TBL_MSG_SEND_BATCH
CREATE TABLE IF NOT EXISTS `TBL_MSG_SEND_BATCH`
(
    `BATCH_CODE`    INT PRIMARY KEY AUTO_INCREMENT COMMENT '발송 배치 코드',
    `SHOP_CODE`     INT         NOT NULL COMMENT '샵 코드',
    `TEMPLATE_CODE` INT COMMENT '사용된 템플릿 코드',
    `SEND_DATE`     DATE        NOT NULL COMMENT '발송 날짜',
    `SEND_TIME`     TIME        NOT NULL COMMENT '발송 시간',
    `SEND_TYPE`     VARCHAR(20) NOT NULL COMMENT '발송 타입 (INDIVIDUAL, GROUP)',

    `SUBJECT`       VARCHAR(100) COMMENT '메시지 제목/요약',

    `TOTAL_COUNT`   INT       DEFAULT 0 COMMENT '총 발송 건수',
    `SUCCESS_COUNT` INT       DEFAULT 0 COMMENT '성공 건수',
    `FAIL_COUNT`    INT       DEFAULT 0 COMMENT '실패 건수',
    `CREATED_AT`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_shop_batch (`SHOP_CODE`, `BATCH_CODE`),
    INDEX idx_shop_date (`SHOP_CODE`, `SEND_DATE`),
    INDEX idx_created_at (CREATED_AT)
);

-- SHOP_MSG_HISTORY table
CREATE TABLE IF NOT EXISTS `TBL_SHOP_MSG_HISTORY`
(
    `HISTORY_CODE`  INT PRIMARY KEY AUTO_INCREMENT COMMENT '히스토리 코드',
    `BATCH_CODE`    INT         NOT NULL COMMENT '발송 배치 코드',
    `USER_CODE`     INT         NOT NULL COMMENT '수신자',
    `MSG_CONTENT`   TEXT        NOT NULL COMMENT '실제 발송된 메시지 내용',
    `SEND_STATUS`   VARCHAR(20) NOT NULL COMMENT '발송 상태 (PENDING, SUCCESS, FAIL)',
    `ERROR_MESSAGE` VARCHAR(255) COMMENT '오류 메시지',
    `SENT_AT`       TIMESTAMP COMMENT '실제 발송 시간',

    FOREIGN KEY (`BATCH_CODE`) REFERENCES `TBL_MSG_SEND_BATCH` (`BATCH_CODE`) ON DELETE CASCADE,
    INDEX idx_batch_code (`BATCH_CODE`),
    INDEX idx_user_code (`USER_CODE`),
    INDEX idx_send_status (`SEND_STATUS`),
    INDEX idx_history_user (`HISTORY_CODE`, `USER_CODE`)
);

-- Set Foreign Key Constraints
ALTER TABLE `TBL_SHOP`
    ADD CONSTRAINT `FK_TBL_SHOP_CATEGORY_TO_SHOP_1` FOREIGN KEY (`CATEGORY_CODE`) REFERENCES `TBL_SHOP_CATEGORY` (`CATEGORY_CODE`);
ALTER TABLE `TBL_SHOP`
    ADD CONSTRAINT `FK_TBL_USER_TO_SHOP_1` FOREIGN KEY (`ADMIN_CODE`) REFERENCES `TBL_USER` (`USER_CODE`);

-- TBL_SHOP_HOLIDAY에 대한 FK(SHOP_CODE) 추가
ALTER TABLE `TBL_SHOP_HOLIDAY`
    ADD CONSTRAINT `FK_TBL_SHOP_TO_SHOP_HOLIDAY_1` FOREIGN KEY (`SHOP_CODE`) REFERENCES `TBL_SHOP` (`SHOP_CODE`);

-- Modified FK for MENU_CATEGORY (now references SHOP table)
ALTER TABLE `TBL_MENU_CATEGORY`
    ADD CONSTRAINT `FK_TBL_SHOP_TO_MENU_CATEGORY_1` FOREIGN KEY (`SHOP_CODE`) REFERENCES `TBL_SHOP` (`SHOP_CODE`);

-- Modified FK for MENU (now references MENU_CATEGORY with composite key)
ALTER TABLE `TBL_MENU`
    ADD CONSTRAINT `FK_TBL_MENU_CATEGORY_TO_MENU_1` FOREIGN KEY (`CATEGORY_CODE`, `SHOP_CODE`) REFERENCES `TBL_MENU_CATEGORY` (`CATEGORY_CODE`, `SHOP_CODE`);

ALTER TABLE `TBL_MESSAGE_TEMPLATE`
    ADD CONSTRAINT `FK_TBL_SHOP_TO_MESSAGE_TEMPLATE_1` FOREIGN KEY (`SHOP_CODE`) REFERENCES `TBL_SHOP` (`SHOP_CODE`);

ALTER TABLE `TBL_RESERVATION`
    ADD CONSTRAINT `FK_TBL_USER_TO_RESERVATION_1` FOREIGN KEY (`USER_CODE`) REFERENCES `TBL_USER` (`USER_CODE`);
ALTER TABLE `TBL_RESERVATION`
    ADD CONSTRAINT `FK_TBL_SHOP_TO_RESERVATION_1` FOREIGN KEY (`SHOP_CODE`) REFERENCES `TBL_SHOP` (`SHOP_CODE`);
ALTER TABLE `TBL_RESERVATION`
    ADD CONSTRAINT `FK_TBL_MENU_TO_RESERVATION_1` FOREIGN KEY (`MENU_CODE`) REFERENCES `TBL_MENU` (`MENU_CODE`);

ALTER TABLE `TBL_SALES`
    ADD CONSTRAINT `FK_TBL_RESERVATION_TO_SALES_1` FOREIGN KEY (`RESV_CODE`) REFERENCES `TBL_RESERVATION` (`RESV_CODE`);

ALTER TABLE `TBL_VISITORS`
    ADD CONSTRAINT `FK_TBL_USER_TO_VISITORS_1` FOREIGN KEY (`USER_CODE`) REFERENCES `TBL_USER` (`USER_CODE`);
ALTER TABLE `TBL_VISITORS`
    ADD CONSTRAINT `FK_TBL_SHOP_TO_VISITORS_1` FOREIGN KEY (`SHOP_CODE`) REFERENCES `TBL_SHOP` (`SHOP_CODE`);

ALTER TABLE `TBL_SHOP_MSG_HISTORY`
    ADD CONSTRAINT `FK_TBL_USER_TO_SHOP_MSG_HISTORY_1` FOREIGN KEY (`USER_CODE`) REFERENCES `TBL_USER` (`USER_CODE`);
ALTER TABLE `TBL_SHOP_MSG_HISTORY`
    ADD CONSTRAINT `FK_TBL_MSG_SEND_BATCH_TO_SHOP_MSG_HISTORY_1` FOREIGN KEY (`BATCH_CODE`) REFERENCES `TBL_MSG_SEND_BATCH` (`BATCH_CODE`);

ALTER TABLE `TBL_MSG_SEND_BATCH`
    ADD CONSTRAINT `FK_TBL_MESSAGE_TEMPLATE_TO_MSG_SEND_BATCH_1` FOREIGN KEY (`TEMPLATE_CODE`) REFERENCES `TBL_MESSAGE_TEMPLATE` (`TEMPLATE_CODE`);
ALTER TABLE `TBL_MSG_SEND_BATCH`
    ADD CONSTRAINT `FK_TBL_SHOP_TO_MSG_SEND_BATCH_1` FOREIGN KEY (`SHOP_CODE`) REFERENCES `TBL_SHOP` (`SHOP_CODE`);
